package com.rvho.cxfclient.wsdl.cxf.wsexternal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-15T14:23:07.059+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "EasyMonitorDataOperation", 
                  wsdlLocation = "http://127.0.0.1:8080/easy_ws_01/ws/EasyMonitorDataOperation?wsdl",
                  targetNamespace = "http://impl.ws.easy.dnion.com/") 
public class EasyMonitorDataOperation extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.easy.dnion.com/", "EasyMonitorDataOperation");
    public final static QName EasyMonitorWSImplPort = new QName("http://impl.ws.easy.dnion.com/", "EasyMonitorWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/easy_ws_01/ws/EasyMonitorDataOperation?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EasyMonitorDataOperation.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/easy_ws_01/ws/EasyMonitorDataOperation?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EasyMonitorDataOperation(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EasyMonitorDataOperation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EasyMonitorDataOperation() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EasyMonitorDataOperation(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EasyMonitorDataOperation(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EasyMonitorDataOperation(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EasyMonitorDataWS
     */
    @WebEndpoint(name = "EasyMonitorWSImplPort")
    public EasyMonitorDataWS getEasyMonitorWSImplPort() {
        return super.getPort(EasyMonitorWSImplPort, EasyMonitorDataWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EasyMonitorDataWS
     */
    @WebEndpoint(name = "EasyMonitorWSImplPort")
    public EasyMonitorDataWS getEasyMonitorWSImplPort(WebServiceFeature... features) {
        return super.getPort(EasyMonitorWSImplPort, EasyMonitorDataWS.class, features);
    }

}
