package com.rvho.cxfclient.wsdl.cxf.wsexternal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-15T14:23:07.045+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://ws.easy.dnion.com/", name = "EasyMonitorDataWS")
@XmlSeeAlso({ObjectFactory.class})
public interface EasyMonitorDataWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getIpInfo", targetNamespace = "http://ws.easy.dnion.com/", className = "com.rvho.cxfclient.wsdl.cxf.wsexternal.GetIpInfo")
    @WebMethod
    @ResponseWrapper(localName = "getIpInfoResponse", targetNamespace = "http://ws.easy.dnion.com/", className = "com.rvho.cxfclient.wsdl.cxf.wsexternal.GetIpInfoResponse")
    public java.lang.String getIpInfo(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getImOutbandwidth", targetNamespace = "http://ws.easy.dnion.com/", className = "com.rvho.cxfclient.wsdl.cxf.wsexternal.GetImOutbandwidth")
    @WebMethod
    @ResponseWrapper(localName = "getImOutbandwidthResponse", targetNamespace = "http://ws.easy.dnion.com/", className = "com.rvho.cxfclient.wsdl.cxf.wsexternal.GetImOutbandwidthResponse")
    public java.lang.String getImOutbandwidth(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getIpOutbandwidth", targetNamespace = "http://ws.easy.dnion.com/", className = "com.rvho.cxfclient.wsdl.cxf.wsexternal.GetIpOutbandwidth")
    @WebMethod
    @ResponseWrapper(localName = "getIpOutbandwidthResponse", targetNamespace = "http://ws.easy.dnion.com/", className = "com.rvho.cxfclient.wsdl.cxf.wsexternal.GetIpOutbandwidthResponse")
    public java.lang.String getIpOutbandwidth(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOutbandwidth", targetNamespace = "http://ws.easy.dnion.com/", className = "com.rvho.cxfclient.wsdl.cxf.wsexternal.GetOutbandwidth")
    @WebMethod
    @ResponseWrapper(localName = "getOutbandwidthResponse", targetNamespace = "http://ws.easy.dnion.com/", className = "com.rvho.cxfclient.wsdl.cxf.wsexternal.GetOutbandwidthResponse")
    public java.lang.String getOutbandwidth(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    );
}
