
package com.rvho.cxfclient.wsdl.cxf.wsexternal;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-15T14:23:06.982+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class EasyMonitorDataWS_EasyMonitorWSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.easy.dnion.com/", "EasyMonitorDataOperation");

    private EasyMonitorDataWS_EasyMonitorWSImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EasyMonitorDataOperation.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EasyMonitorDataOperation ss = new EasyMonitorDataOperation(wsdlURL, SERVICE_NAME);
        EasyMonitorDataWS port = ss.getEasyMonitorWSImplPort();  
        
        {
        System.out.println("Invoking getIpInfo...");
        java.lang.String _getIpInfo_json = "";
        java.lang.String _getIpInfo__return = port.getIpInfo(_getIpInfo_json);
        System.out.println("getIpInfo.result=" + _getIpInfo__return);


        }
        {
        System.out.println("Invoking getImOutbandwidth...");
        java.lang.String _getImOutbandwidth_json = "";
        java.lang.String _getImOutbandwidth__return = port.getImOutbandwidth(_getImOutbandwidth_json);
        System.out.println("getImOutbandwidth.result=" + _getImOutbandwidth__return);


        }
        {
        System.out.println("Invoking getIpOutbandwidth...");
        java.lang.String _getIpOutbandwidth_json = "";
        java.lang.String _getIpOutbandwidth__return = port.getIpOutbandwidth(_getIpOutbandwidth_json);
        System.out.println("getIpOutbandwidth.result=" + _getIpOutbandwidth__return);


        }
        {
        System.out.println("Invoking getOutbandwidth...");
        java.lang.String _getOutbandwidth_json = "";
        java.lang.String _getOutbandwidth__return = port.getOutbandwidth(_getOutbandwidth_json);
        System.out.println("getOutbandwidth.result=" + _getOutbandwidth__return);


        }

        System.exit(0);
    }

}
